spring:
  application:
    name: "spring-cloud-service-provider"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    data-password: 123456
      #zipkin:
      #base-url: "http://localhost:9411"  #服务追踪需要的配置，每个服务都需要配置
      #boot:
      #admin:
      #client:
    #url: http://localhost/8084
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
  client:
    serverUrl:
      defaultZone: "http://localhost:8761/eureka"
mybatis:
  mapper-locations: classpath:mapper/*.xml