spring:
  application:
    name: "spring-cloud-feign-consumer"
server:
  port: 8765




#feign熔断器开启配置
feign:
  hystrix:
    enabled: true

#eureka发现配置
eureka:
  client:
    serverUrl: "http://localhost:8761/eureka"

